AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - org.thesaastech::chart-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  ChartLambdaNativeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtimei
      Runtime: provided
      CodeUri: target/function.zip
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Timeout: 20
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        GetChartSummary:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /chart
            Method: GET
        GetChartForCountry:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /chart/{countryName}
            Method: GET


Outputs:
  ChartLambdaNativeApi:
    Description: URL for application
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/chart'
    Export:
      Name: ChartLambdaNativeApi
