  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - org.thesaastech::chart-lambda
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    ApiGatewayApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: prod

    ChartLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java8
        CodeUri: target/chart-lambda-1.0-SNAPSHOT-runner.jar
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Events:
          GetChartSummary:
            Type: Api
            Properties:
              RestApiId: !Ref ApiGatewayApi
              Path: /chart
              Method: GET
          GetChartForCountry:
            Type: Api
            Properties:
              RestApiId: !Ref ApiGatewayApi
              Path: /chart/{countryName}
              Method: GET
  Outputs:
    ChartLambdaApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/chart'
      Export:
        Name: ChartLambdaApi
